#!/usr/bin/python3
import sys
import time


def factorize_input(n):
    """ a function that takes a number.

    Args:
        n (int): the input number.

    Return:
        the two factors of the number.
    """
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return (i, n // i)

    return None


def main(file_input):
    """ a function that reads the input file and performs factorization.
    """
    try:
        with open(file_input, 'r') as file:
            start_time = time.time()
            for line in file:
                n = int(line)
                f = factorize_input(n)
                if f:
                    print(f"{n}={f[0]}*{f[1]}")

    except FileNotFoundError:
        print("Error: File {} not found".format(file_input))
        exit()

    if time.time() - start_time > 5:
        print("Error: Time Limit exceeded")
        exit()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    file_input = sys.argv[1]
    main(file_input)
