#!/usr/bin/python3
import argparse


def fact_number(n):
    # a function that Factorizes as many numbers as possible
    # into a product of two smaller numbers.
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return (i, n // i)
    return None


def main(file_input):
    try:
        with open(file_input, 'r') as file:
            for line in file:
                n = int(line)
                factr = fact_number(n)
                if factr:
                    print(f"{n}={factr[0]}*{factr[1]}")
    except FileNotFoundError:
        print("Error: File {} not found".format(file_input))
        exit()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='factors <file>',
        description='Factorize numbers from a file'
    )
    parser.add_argument(
        'file',
        help='a file containing natural numbers to factor'
    )

    args = parser.parse_args()
    main(args.file)
