#!/usr/bin/python3
import sys


class NumberFactorizer:
    def __init__(self, n):
        """
        Initialize the NumberFactorizer object.

        Args:
            n (int): the input number to factorize.
        """
        self.n = n

    def is_prime(self, num):
        """ Check if a number is prime.

        Args:
            num (int): the number to check.

        Returns:
            True if it is a prime number, otherwise False.
        """
        if num <= 1:
            return False
        if num == 2:
            return True
        if num % 2 == 0:
            return False
        i = 3
        while i * i <= num:
            if num % i == 0:
                return False
            i += 2
        return True

    def pollardsRho(self):
        """ Find prime factor of a number using Pollard's rho algorithm.

        Returns:
            int: the prime factor, or None if no factor is found.
        """
        x = 2
        y = 2
        d = 1

        func = lambda x: (x * x + 1) % self.n

        while d == 1:
            x = func(x)
            y = func(func(y))
            d = self.hcf(abs(x - y), self.n)

        if d == self.n:
            return None
        else:
            return d

    def factorize_number(self):
        """ Factorize the given number into its two prime factors.

        Returns:
            tuple: as a tuple (p, q), the two prime factors.
        """
        p = self.pollardsRho()
        if p is None:
            return None

        q = self.n // p
        if self.is_prime(p) and self.is_prime(q):
            return (p, q)
        else:
            return None

    def hcf(self, x, y):
        """ Calculate the highest common factor (hcf) of two numbers.

        Args:
            x (int): the first number.
            y (int): the seconde number.

        Returns:
            int: the hcf
        """
        while y != 0:
            x, y = y, x % y
        return x


def main():
    """ Read and factorize the number inside the input file.
    """
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    try:
        file_input = sys.argv[1]
        with open(file_input, 'r') as file:
            n = int(file.readline().strip())
            factorizer = NumberFactorizer(n)
            num_factors = factorizer.factorize_number()
            if num_factors:
                p, q = num_factors
                print(f"{n}={p}*{q}")
            else:
                print("No prime factors found")

    except FileNotFoundError:
        print("Error: File not found")
        sys.exit(1)


if __name__ == "__main__":
    main()
